<a href="https://colab.research.google.com/github/Subuktageen-Farooqi/ms_course_deeplearning/blob/main/ms_deeplearning_tutorial_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import pandas as pd
from sklearn.utils import shuffle

In [7]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', header=None)

df = shuffle(df)

df.head()

0    1    2    3                4
102  7.1  3.0  5.9  2.1   Iris-virginica
24   4.8  3.4  1.9  0.2      Iris-setosa
47   4.6  3.2  1.4  0.2      Iris-setosa
14   5.8  4.0  1.2  0.2      Iris-setosa
89   5.5  2.5  4.0  1.3  Iris-versicolor

In [8]:
X = df.iloc[:, 0:4].values
y = df.iloc[:, 4].values
print(X[0:5])
print(y[0:5])


[[7.1 3.  5.9 2.1]
 [4.8 3.4 1.9 0.2]
 [4.6 3.2 1.4 0.2]
 [5.8 4.  1.2 0.2]
 [5.5 2.5 4.  1.3]]
['Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor']


In [9]:
from sklearn.model_selection import train_test_split

train_data, test_data, train_labels, test_labels = train_test_split(X,y, test_size=0.25)

train_labels = np.where(train_labels == 'Iris-setosa', 1, -1)
test_labels = np.where(test_labels == 'Iris-setosa', 1, -1)

print('Train Data', train_data[0:2])
print('Trains Labels', train_labels[0:2])

print('Test Data', test_data[0:2])
print('Test Labels', test_labels[0:2])

Train Data [[6.9 3.1 4.9 1.5]
 [6.8 3.  5.5 2.1]]
Trains Labels [-1 -1]
Test Data [[5.6 2.9 3.6 1.3]
 [5.5 2.5 4.  1.3]]
Test Labels [-1 -1]


In [55]:
class Perceptron(object):
  def __init__(self, learning_rate = 0.2, iterations = 10):
    self.learning_rate = learning_rate
    self.n_iterations = iterations

  def weighted_sum(X, self):
    return np.dot(X, self.weights[1:]) + self.weights[0] # a = wx + b

  def predict(self, X):
    return np.where(self.weighted_sum(X) >= 0.0, 1, -1)

  def fit(self, X, y):
    self.weights = np.zeros(1 + X.shape[1])
    self.errors = []

    print("Weights", self.weights)

    for _ in range(self.n_iterations):
        error = 0

        for xi,y in zip(X,y):
          y_pred = self.predict(xi)

          update = self.learning_rate * (y - y_pred)


          self.weights[1:] = self.weights[1:] + update * xi
          print("updated weights: ", self.weights[1:])


          self.weights[0] - self.weights[0] + update


          error += int(update != 0.0)

        self.errors.append(error)

In [56]:
from sklearn.linear_model import Perceptron

perceptron = Perceptron(eta0 = 0.1, max_iter = 10)
perceptron.fit(train_data, train_labels)

test_preds = perceptron.predict(test_data)
print(test_preds)



[-1 -1  1  1  1 -1  1  1 -1 -1  1 -1  1 -1 -1 -1 -1 -1 -1 -1  1 -1  1 -1
 -1 -1 -1  1 -1  1 -1 -1  1 -1  1  1 -1 -1]


In [57]:
from sklearn.metrics import accuracy_score

y_preds = perceptron.predict(test_data)
accuracy = accuracy_score(y_preds, test_labels)
print('Accuracy:', round(accuracy, 2) * 100, "%")

Accuracy: 100.0 %


In [58]:
user_input = np.zeros([4])
features = [ 'Sepal Length','Sepal Width','Petal Length','Petal Width']
for i in range(4):
  user_input[i] = input(f"Enter value {features[i]}: ")


Enter value Sepal Length: 2.1
Enter value Sepal Width: 2.1
Enter value Petal Length: 2.1
Enter value Petal Width: 2.1


In [59]:
single_prediction = perceptron.predict(np.array(user_input).reshape(1, -1))
print(f"Model's Prediction: {single_prediction} - { 'Iris setosa' if single_prediction == 1 else 'not Iris Setosa' }")

Model's Prediction: [-1] - not Iris Setosa


In [60]:
def predict_with_sigmoid(self, X):
  print('used')
  return 1/(1 + np.exp(-self.weighted_sum(X)) >= 0.0, 1,0)
perceptron.predict = predict_with_sigmoid

In [61]:
def sigmoid(z):
  print('used')
  return 1/(1 + np.exp(-z))
perceptron.predict = sigmoid
single_prediction = perceptron.predict(np.array(user_input).reshape(-1, 1))
print(single_prediction)
# print(f"Model's Prediction: {single_prediction} - { 'Iris setosa' if single_prediction == 1 else 'not Iris Setosa' }")

used
[[0.89090318]
 [0.89090318]
 [0.89090318]
 [0.89090318]]
