<a href="https://colab.research.google.com/github/Subuktageen-Farooqi/ms_course_deeplearning/blob/main/ms_deeplearning_tutorial_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.utils import shuffle

In [49]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', header=None)

df = shuffle(df)

df.head()

,0,1,2,3,4
112,6.8,3.0,5.5,2.1,Iris-virginica
56,6.3,3.3,4.7,1.6,Iris-versicolor
135,7.7,3.0,6.1,2.3,Iris-virginica
93,5.0,2.3,3.3,1.0,Iris-versicolor
118,7.7,2.6,6.9,2.3,Iris-virginica


In [50]:
X = df.iloc[:, 0:4].values
y = df.iloc[:, 4].values
print(X[0:5])
print(y[0:5])


[[6.8 3.  5.5 2.1]
 [6.3 3.3 4.7 1.6]
 [7.7 3.  6.1 2.3]
 [5.  2.3 3.3 1. ]
 [7.7 2.6 6.9 2.3]]
['Iris-virginica' 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor'
 'Iris-virginica']


In [61]:
from sklearn.model_selection import train_test_split

train_data, test_data, train_labels, test_labels = train_test_split(X, y, test_size=0.25)

train_labels = np.where(train_labels == 'Iris-setosa', 1, -1)
test_labels = np.where(test_labels == 'Iris-setosa', 1, -1)

print('Train Data\n', train_data[0:2])
print('Trains Labels', np.unique(train_labels))

print('Test Data\n', test_data[0:2])
print('Test Labels', np.unique(test_labels))

Train Data
 [[6.3 2.9 5.6 1.8]
 [6.4 3.2 4.5 1.5]]
Trains Labels [-1  1]
Test Data
 [[6.  3.4 4.5 1.6]
 [6.1 3.  4.6 1.4]]
Test Labels [-1  1]


In [62]:
class Perceptron(object):
  def __init__(self, learning_rate = 0.2, iterations = 10):
    self.learning_rate = learning_rate
    self.n_iterations = iterations

  def weighted_sum(self, X):
    return np.dot(X, self.weights[1:]) + self.weights[0] # a = wx + b

  def predict(self, X):
    return np.where(self.weighted_sum(X) >= 0.0, 1, -1)

  def fit(self, X, y):
    #print(f"DEBUG IN FIT: Type of X: {type(X)}, Shape: {X.shape}")
    #print(f"DEBUG IN FIT: Type of y: {type(y)}, Shape: {y.shape}")

    self.weights = np.zeros(1 + X.shape[1])
    self.errors = []

    #print("Weights", self.weights)

    for _ in range(self.n_iterations):
        error = 0

        for xi, label in zip(X, y): # Renamed inner loop 'y' to 'label'
          y_pred = self.predict(xi)

          update = self.learning_rate * (label - y_pred) # Use 'label' here


          self.weights[1:] = self.weights[1:] + update * xi
          # print("updated weights: ", self.weights[1:]) # Commented out to reduce verbose output during debugging


          self.weights[0] = self.weights[0] + update


          error += int(update != 0.0)

        self.errors.append(error)

In [63]:
#from sklearn.linear_model import Perceptron
"""NOTE - this line was causing further code to not use our custom Perceptron rather sklearn library's
pre-built perceptron. See ADDITIONAL TASK at the end for perceptron implementation with sklearn"""
perceptron = Perceptron(learning_rate = 0.1, iterations = 10) # Changed arguments to match custom Perceptron
perceptron.fit(train_data, train_labels)

test_preds = perceptron.predict(test_data)
print("Test Predictions: ", test_preds)

Test Predictions:  [-1 -1 -1  1  1 -1 -1  1 -1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1  1 -1 -1
 -1 -1  1 -1 -1  1 -1 -1  1  1  1  1  1 -1]


In [64]:
from sklearn.metrics import accuracy_score

#y_preds = perceptron.predict(test_data) round(accuracy, 2)
accuracy = accuracy_score(test_preds, test_labels)
print('Accuracy:', accuracy * 100, "%")

Accuracy: 100.0 %


Task 01<br>
Take manual input for the four features (sepal length, sepal width,
petal length, and petal width).

*   Use the model to predict whether it's Iris-setosa or not based on the manually provided values
*   Display the prediction result

In [32]:
user_input = np.zeros([4])
features = [ 'Sepal Length','Sepal Width','Petal Length','Petal Width']
for i in range(4):
  user_input[i] = input(f"Enter value {features[i]}: ")
# Data -> 43|	5.0	3.5	1.6	0.6	|Iris-setosa

Enter value Sepal Length: 5.0
Enter value Sepal Width: 3.5
Enter value Petal Length: 1.6
Enter value Petal Width: 0.6


In [33]:
single_prediction = perceptron.predict(np.array(user_input).reshape(1, -1))
print(f"Model's Prediction: {single_prediction} - { 'Iris setosa' if single_prediction == 1 else 'not Iris Setosa' }")

Model's Prediction: [1] - Iris setosa


Task 02<br>Replace the Step Function with Sigmoid.


In [39]:
def predict_with_sigmoid(self, X):

  # First, calculate the weighted sum
  z = self.weighted_sum(X)
  # Apply the sigmoid function to get probabilities between 0 and 1
  sigmoid_output = 1 / (1 + np.exp(-z))
  # Classify based on a threshold (e.g., 0.5), returning 1 or -1
  return np.where(sigmoid_output >= 0.5, 1, -1)


perceptron.predict = predict_with_sigmoid
single_prediction = perceptron.predict(perceptron, np.array(user_input).reshape(1, -1))
print(f"Model's Prediction: {single_prediction} - { 'Iris setosa' if single_prediction == 1 else 'not Iris Setosa' }")

Model's Prediction: [1] - Iris setosa


Task 03<br>Replace the labels of 1,-1 with 1 & 0

In [40]:
def predict_with_sigmoid(self, X):

  z = self.weighted_sum(X)
  sigmoid_output = 1 / (1 + np.exp(-z))
  # Classify based on a threshold (e.g., 0.5), returning 1 or 0
  return np.where(sigmoid_output >= 0.5, 1, 0)

perceptron.predict = predict_with_sigmoid
single_prediction = perceptron.predict(perceptron, np.array(user_input).reshape(1, -1))
print(f"Model's Prediction: {single_prediction} - { 'Iris setosa' if single_prediction == 1 else 'not Iris Setosa' }")

Model's Prediction: [1] - Iris setosa


Additional Task

In [66]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

print("--- scikit-learn Logistic Regression (Perceptron with Sigmoid Activation) Pipeline ---")

# Adjust labels to 1 (for Iris-setosa) and 0 (for not Iris-setosa) for Logistic Regression
train_labels = np.where(train_labels == 1 , 1, 0)
test_labels = np.where(test_labels == 1, 1, 0)

print('Trains Labels', np.unique(train_labels))
print('Test Labels', np.unique(test_labels))

# 1. Feature Scaling (important for Logistic Regression)
scaler = StandardScaler()
train_data_scaled = scaler.fit_transform(train_data)
test_data_scaled = scaler.transform(test_data)

print("\nScaled Training Data (first 2 samples):\n", train_data_scaled[0:2])
print("Scaled Test Data (first 2 samples):\n", test_data_scaled[0:2])

# 2. Initialize and Train Logistic Regression Model
# LogisticRegression uses sigmoid activation by default for binary classification
log_reg_model = LogisticRegression(random_state=42, max_iter=200)
log_reg_model.fit(train_data_scaled, train_labels)

print("\nLogistic Regression Model Trained.")

# 3. Make Predictions on the Test Set
sklearn_test_preds = log_reg_model.predict(test_data_scaled)
sklearn_test_proba = log_reg_model.predict_proba(test_data_scaled) # Probabilities

print("\nTest Predictions (first 5):", sklearn_test_preds[0:5])
print("Test Probabilities (first 5):\n", sklearn_test_proba[0:5])

# 4. Evaluate the Model
sklearn_accuracy = accuracy_score(test_labels, sklearn_test_preds)
print(f"\nscikit-learn Logistic Regression Accuracy: {sklearn_accuracy * 100:.2f}%")

# 5. Predict on Manual User Input
# Ensure user_input is scaled before prediction
user_input_scaled = scaler.transform(np.array(user_input).reshape(1, -1))
single_prediction_sklearn = log_reg_model.predict(user_input_scaled)
single_proba_sklearn = log_reg_model.predict_proba(user_input_scaled)

prediction_label = 'Iris setosa' if single_prediction_sklearn[0] == 1 else 'not Iris Setosa'
print(f"\nModel's Prediction for user input: {single_prediction_sklearn[0]} - {prediction_label}")
print(f"Probability of being Iris Setosa: {single_proba_sklearn[0][1]:.4f}")

--- scikit-learn Logistic Regression (Perceptron with Sigmoid Activation) Pipeline ---
Trains Labels [-1  1]
Test Labels [-1  1]
Trains Labels [0 1]
Test Labels [0 1]

Scaled Training Data (first 2 samples):
 [[ 0.4993328  -0.29664388  1.01594774  0.79566088]
 [ 0.61633128  0.39075159  0.39447425  0.39424638]]
Scaled Test Data (first 2 samples):
 [[ 0.14833736  0.84901523  0.39447425  0.52805121]
 [ 0.26533584 -0.06751205  0.45097184  0.26044155]]

Logistic Regression Model Trained.

Test Predictions (first 5): [0 0 0 1 1]
Test Probabilities (first 5):
 [[0.95924793 0.04075207]
 [0.98142153 0.01857847]
 [0.99540902 0.00459098]
 [0.03691212 0.96308788]
 [0.05256914 0.94743086]]

scikit-learn Logistic Regression Accuracy: 100.00%

Model's Prediction for user input: 1 - Iris setosa
Probability of being Iris Setosa: 0.9538
